/*
 * JERP 3.0 - Payroll & ERP System
 * Copyright (c) 2026 ninoyerbas. All Rights Reserved.
 * 
 * PROPRIETARY AND CONFIDENTIAL
 * 
 * This source code is the confidential and proprietary information of ninoyerbas.
 * Unauthorized copying, modification, distribution, or use is strictly prohibited.
 * 
 * For licensing inquiries: licensing@jerp.io
 */

using System.ComponentModel.DataAnnotations;
using JERP.Core.Enums;

namespace JERP.Core.Entities.Finance;

/// <summary>
/// Represents a journal entry with multiple line items
/// </summary>
public class JournalEntry : BaseEntity
{
    /// <summary>
    /// Foreign key to the company
    /// </summary>
    [Required]
    public Guid CompanyId { get; set; }

    /// <summary>
    /// Date of the journal entry
    /// </summary>
    [Required]
    public DateTime EntryDate { get; set; }

    /// <summary>
    /// Journal entry number/reference
    /// </summary>
    [MaxLength(50)]
    public string? ReferenceNumber { get; set; }

    /// <summary>
    /// Description/memo for the journal entry
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// Status of the journal entry
    /// </summary>
    [Required]
    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.Draft;

    /// <summary>
    /// Whether this entry was auto-posted from payroll
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// Optional reference to source entity (e.g., PayrollRecord ID)
    /// </summary>
    public Guid? SourceEntityId { get; set; }

    /// <summary>
    /// Source entity type (e.g., "PayrollRecord", "Bill", "Invoice")
    /// </summary>
    [MaxLength(100)]
    public string? SourceEntityType { get; set; }

    /// <summary>
    /// User who posted the entry
    /// </summary>
    public Guid? PostedById { get; set; }

    /// <summary>
    /// Date when the entry was posted
    /// </summary>
    public DateTime? PostedAt { get; set; }

    // Navigation properties
    public Company Company { get; set; } = null!;
    public User? PostedBy { get; set; }
    public ICollection<GeneralLedgerEntry> LedgerEntries { get; set; } = new List<GeneralLedgerEntry>();
}
