/*
 * JERP 3.0 - Payroll & ERP System
 * Copyright (c) 2026 ninoyerbas. All Rights Reserved.
 * 
 * PROPRIETARY AND CONFIDENTIAL
 * 
 * This source code is the confidential and proprietary information of ninoyerbas.
 * Unauthorized copying, modification, distribution, or use is strictly prohibited.
 * 
 * For licensing inquiries: licensing@jerp.io
 */

using JERP.Core.Entities;
using JERP.Core.Entities.Finance;
using JERP.Core.Enums;
using JERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace JERP.Application.Services.Finance;

/// <summary>
/// Service for automatically posting payroll transactions to the general ledger
/// </summary>
public class PayrollToFinanceService : IPayrollToFinanceService
{
    private readonly JerpDbContext _context;
    private readonly IGeneralLedgerService _ledgerService;
    private readonly IAccountService _accountService;
    private readonly ILogger<PayrollToFinanceService> _logger;

    public PayrollToFinanceService(
        JerpDbContext context,
        IGeneralLedgerService ledgerService,
        IAccountService accountService,
        ILogger<PayrollToFinanceService> logger)
    {
        _context = context;
        _ledgerService = ledgerService;
        _accountService = accountService;
        _logger = logger;
    }

    public async Task PostPayrollToGeneralLedgerAsync(Guid payPeriodId)
    {
        _logger.LogInformation("Posting payroll to general ledger for pay period {PayPeriodId}", payPeriodId);

        var payPeriod = await _context.PayPeriods
            .Include(p => p.Company)
            .FirstOrDefaultAsync(p => p.Id == payPeriodId && !p.IsDeleted);

        if (payPeriod == null)
        {
            throw new InvalidOperationException($"Pay period {payPeriodId} not found");
        }

        var payrollRecords = await _context.PayrollRecords
            .Where(r => r.PayPeriodId == payPeriodId && !r.IsDeleted)
            .ToListAsync();

        // Get accounts needed for payroll posting
        var payrollExpenseAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "6100", "Payroll Expense", AccountType.Expense, false);
        var payrollTaxExpenseAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "6200", "Payroll Tax Expense", AccountType.Expense, false);
        var cashAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "1000", "Cash - Operating", AccountType.Asset, false);
        var taxLiabilityAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "2100", "Tax Liabilities Payable", AccountType.Liability, false);
        var deductionsPayableAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "2200", "Deductions Payable", AccountType.Liability, false);

        // Calculate totals
        var totalGrossPay = payrollRecords.Sum(r => r.GrossPay);
        var totalEmployeeTaxes = payrollRecords.Sum(r => r.TotalTaxes);
        var totalDeductions = payrollRecords.Sum(r => r.TotalDeductions);
        var totalNetPay = payrollRecords.Sum(r => r.NetPay);

        // Calculate employer taxes (matching portion of FICA)
        var employerSocialSecurity = payrollRecords.Sum(r => r.SocialSecurityTax);
        var employerMedicare = payrollRecords.Sum(r => r.MedicareTax);
        var totalEmployerTaxes = employerSocialSecurity + employerMedicare;

        // Create journal entry
        var journalEntry = new JournalEntry
        {
            CompanyId = payPeriod.CompanyId,
            EntryDate = payPeriod.PayDate,
            ReferenceNumber = $"PAYROLL-{payPeriod.StartDate:yyyyMMdd}",
            Description = $"Payroll for period {payPeriod.StartDate:yyyy-MM-dd} to {payPeriod.EndDate:yyyy-MM-dd}",
            Status = JournalEntryStatus.Draft,
            IsAutoGenerated = true,
            SourceEntityType = "PayPeriod",
            SourceEntityId = payPeriodId
        };

        var ledgerEntries = new List<GeneralLedgerEntry>();

        // Debit: Payroll Expense (Gross Pay)
        ledgerEntries.Add(new GeneralLedgerEntry
        {
            AccountId = payrollExpenseAccount.Id,
            EntryType = EntryType.Debit,
            Amount = totalGrossPay,
            Description = "Gross payroll expense"
        });

        // Debit: Payroll Tax Expense (Employer portion)
        ledgerEntries.Add(new GeneralLedgerEntry
        {
            AccountId = payrollTaxExpenseAccount.Id,
            EntryType = EntryType.Debit,
            Amount = totalEmployerTaxes,
            Description = "Employer payroll tax expense"
        });

        // Credit: Cash (Net Pay)
        ledgerEntries.Add(new GeneralLedgerEntry
        {
            AccountId = cashAccount.Id,
            EntryType = EntryType.Credit,
            Amount = totalNetPay,
            Description = "Net payroll payment"
        });

        // Credit: Tax Liabilities (Employee + Employer taxes)
        var totalTaxLiability = totalEmployeeTaxes + totalEmployerTaxes;
        ledgerEntries.Add(new GeneralLedgerEntry
        {
            AccountId = taxLiabilityAccount.Id,
            EntryType = EntryType.Credit,
            Amount = totalTaxLiability,
            Description = "Payroll tax liabilities"
        });

        // Credit: Deductions Payable (if any)
        if (totalDeductions > 0)
        {
            ledgerEntries.Add(new GeneralLedgerEntry
            {
                AccountId = deductionsPayableAccount.Id,
                EntryType = EntryType.Credit,
                Amount = totalDeductions,
                Description = "Employee deductions payable"
            });
        }

        // Create and post the journal entry
        await _ledgerService.CreateJournalEntryAsync(journalEntry, ledgerEntries);

        _logger.LogInformation("Payroll posted to general ledger: JournalEntry {JournalEntryId}", journalEntry.Id);
    }

    public async Task PostPayrollRecordToGeneralLedgerAsync(PayrollRecord payrollRecord)
    {
        _logger.LogInformation("Posting single payroll record {PayrollRecordId} to general ledger", payrollRecord.Id);

        var payPeriod = await _context.PayPeriods
            .FirstOrDefaultAsync(p => p.Id == payrollRecord.PayPeriodId && !p.IsDeleted);

        if (payPeriod == null)
        {
            throw new InvalidOperationException($"Pay period for payroll record not found");
        }

        var employee = await _context.Employees
            .FirstOrDefaultAsync(e => e.Id == payrollRecord.EmployeeId && !e.IsDeleted);

        if (employee == null)
        {
            throw new InvalidOperationException($"Employee for payroll record not found");
        }

        // Get accounts
        var payrollExpenseAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "6100", "Payroll Expense", AccountType.Expense, false);
        var payrollTaxExpenseAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "6200", "Payroll Tax Expense", AccountType.Expense, false);
        var cashAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "1000", "Cash - Operating", AccountType.Asset, false);
        var taxLiabilityAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "2100", "Tax Liabilities Payable", AccountType.Liability, false);
        var deductionsPayableAccount = await GetOrCreateAccountAsync(payPeriod.CompanyId, "2200", "Deductions Payable", AccountType.Liability, false);

        // Calculate employer taxes
        var employerSocialSecurity = payrollRecord.SocialSecurityTax;
        var employerMedicare = payrollRecord.MedicareTax;
        var totalEmployerTaxes = employerSocialSecurity + employerMedicare;

        // Create journal entry
        var journalEntry = new JournalEntry
        {
            CompanyId = payPeriod.CompanyId,
            EntryDate = payPeriod.PayDate,
            ReferenceNumber = $"PAY-{employee.EmployeeNumber}-{payPeriod.StartDate:yyyyMMdd}",
            Description = $"Payroll for {employee.FirstName} {employee.LastName} - {payPeriod.StartDate:yyyy-MM-dd}",
            Status = JournalEntryStatus.Draft,
            IsAutoGenerated = true,
            SourceEntityType = "PayrollRecord",
            SourceEntityId = payrollRecord.Id
        };

        var ledgerEntries = new List<GeneralLedgerEntry>
        {
            // Debit: Payroll Expense
            new GeneralLedgerEntry
            {
                AccountId = payrollExpenseAccount.Id,
                EntryType = EntryType.Debit,
                Amount = payrollRecord.GrossPay,
                Description = $"Gross pay - {employee.FirstName} {employee.LastName}"
            },
            // Debit: Payroll Tax Expense
            new GeneralLedgerEntry
            {
                AccountId = payrollTaxExpenseAccount.Id,
                EntryType = EntryType.Debit,
                Amount = totalEmployerTaxes,
                Description = $"Employer taxes - {employee.FirstName} {employee.LastName}"
            },
            // Credit: Cash
            new GeneralLedgerEntry
            {
                AccountId = cashAccount.Id,
                EntryType = EntryType.Credit,
                Amount = payrollRecord.NetPay,
                Description = $"Net pay - {employee.FirstName} {employee.LastName}"
            },
            // Credit: Tax Liabilities
            new GeneralLedgerEntry
            {
                AccountId = taxLiabilityAccount.Id,
                EntryType = EntryType.Credit,
                Amount = payrollRecord.TotalTaxes + totalEmployerTaxes,
                Description = $"Tax liabilities - {employee.FirstName} {employee.LastName}"
            }
        };

        // Add deductions if any
        if (payrollRecord.TotalDeductions > 0)
        {
            ledgerEntries.Add(new GeneralLedgerEntry
            {
                AccountId = deductionsPayableAccount.Id,
                EntryType = EntryType.Credit,
                Amount = payrollRecord.TotalDeductions,
                Description = $"Deductions - {employee.FirstName} {employee.LastName}"
            });
        }

        await _ledgerService.CreateJournalEntryAsync(journalEntry, ledgerEntries);

        _logger.LogInformation("Payroll record posted to general ledger: JournalEntry {JournalEntryId}", journalEntry.Id);
    }

    private async Task<Account> GetOrCreateAccountAsync(Guid companyId, string accountCode, string name, AccountType accountType, bool is280EDeductible)
    {
        var account = await _accountService.GetAccountByCodeAsync(companyId, accountCode);
        
        if (account == null)
        {
            _logger.LogInformation("Creating account {AccountCode} - {Name}", accountCode, name);
            
            account = new Account
            {
                CompanyId = companyId,
                AccountCode = accountCode,
                Name = name,
                AccountType = accountType,
                IsCOGS = accountType == AccountType.COGS,
                Is280EDeductible = is280EDeductible || accountType == AccountType.COGS,
                IsActive = true
            };

            account = await _accountService.CreateAccountAsync(account);
        }

        return account;
    }
}
